# Generated by Django 6.0.5 on 2026-05-08 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection', to='connections.match')),
                ('rejected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections_made', to=settings.AUTH_USER_MODEL)),
                ('rejected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
