# Generated by Django 6.0.5 on 2026-05-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hookup', 'Hookup'), ('hangout', 'Hangout'), ('smokeup', 'Smoke Up'), ('coffee', 'Coffee & Chill')], max_length=10, unique=True)),
                ('male_count', models.PositiveIntegerField(default=0)),
                ('female_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
