# Generated by Django 6.0.5 on 2026-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphoto',
            name='cloudinary_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_photos/'),
        ),
    ]
