# Generated by Django 6.0.5 on 2026-05-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userphoto_cloudinary_image_alter_userphoto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alcohol',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='drugs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('monogamy', 'Monogamy'), ('non-monogamy', 'Non-Monogamy')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='religion',
            field=models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Sikh', 'Sikh'), ('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Jain', 'Jain'), ('Atheist', 'Atheist'), ('Agnostic', 'Agnostic'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sexuality',
            field=models.CharField(blank=True, choices=[('Straight', 'Straight'), ('Gay', 'Gay'), ('Lesbian', 'Lesbian'), ('Bisexual', 'Bisexual'), ('Pansexual', 'Pansexual'), ('Asexual', 'Asexual'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='smoke',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('hookup', 'Hookup'), ('hangout', 'Hangout'), ('smokeup', 'Smoke Up'), ('coffee', 'Coffee & Chill'), ('nightout', 'Night Out'), ('linkup', 'Link Up'), ('tripout', 'Trip Out'), ('workout', 'Workout')], max_length=10),
        ),
    ]
