# Generated by Django 6.0.5 on 2026-05-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_alcohol_user_dob_user_drugs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
