# Generated by Django 6.0.5 on 2026-05-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intent', '0002_userintent_delete_dailyintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintent',
            name='plan_flexibility',
            field=models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ("I Don't Know", "I Don't Know"), ('Up To You', 'Up To You')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userintent',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('hookup', 'Hookup'), ('hangout', 'Hangout'), ('smokeup', 'Smoke Up'), ('coffee', 'Coffee & Chill')], max_length=10),
        ),
    ]
