# Generated by Django 6.0.5 on 2026-05-15 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.PositiveIntegerField(default=18)),
                ('age_max', models.PositiveIntegerField(default=50)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('drinks', models.BooleanField(blank=True, default=None, null=True)),
                ('smokes', models.BooleanField(blank=True, default=None, null=True)),
                ('weed', models.BooleanField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
